services:
  - type: web
    name: filo-torneos
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
      - key: PIP_USE_PEP517
        value: "0"
      - key: PIP_PREFER_BINARY
        value: "1"
    healthCheckPath: /status
    autoDeploy: true 